remote_theme: pmarsceill/just-the-docs #jekyll-theme-yat #pages-themes/modernist@v0.2.0
#theme: jekyll-theme-minimal

title: "Thursday: Massive Stars in Binaries"
description: Jan Eldridge, Ryosuke Hirai, Sohan Ghodla, Ebraheem Farag
url: "https://debraheem.github.io"
baseurl: "/astronuc"



# Kramdown with MathJax Configuration
kramdown:
  math_engine: mathjax


plugins:
  - jekyll-remote-theme
  - jemoji
