remote_theme: pmarsceill/just-the-docs #jekyll-theme-yat #pages-themes/modernist@v0.2.0
#theme: jekyll-theme-minimal

title: "Astronuc: Nuclear Reactions and Networks in Stars with MESA"
description:  Ebraheem Farag
footer_content: ""
color_scheme: dark
url: "https://debraheem.github.io"
baseurl: "/astronuc"

# Sidebar resources section (separate external links block)
nav_external_links:
  - title: "Lab Materials"
    url: "https://drive.google.com/drive/folders/1yFy2I7kBh6UZPYmhFxkZswQVPI0Qavjc?usp=share_link"
  - title: "MESA Docs"
    url: "https://docs.mesastar.org/en/25.12.1/"
  - title: "MESA Instrument Papers"
    url: "https://docs.mesastar.org/en/25.12.1/reference.html"
  - title: "Installation"
    url: "https://docs.mesastar.org/en/25.12.1/installation.html"
  - title: "Star_job Defaults"
    url: "https://docs.mesastar.org/en/25.12.1/reference/star_job.html"
  - title: "Control Defaults"
    url: "https://docs.mesastar.org/en/25.12.1/reference/controls.html"



# Kramdown with MathJax Configuration
kramdown:
  math_engine: mathjax


plugins:
  - jekyll-remote-theme
  - jemoji
