remote_theme: pmarsceill/just-the-docs #jekyll-theme-yat #pages-themes/modernist@v0.2.0
#theme: jekyll-theme-minimal

title: "Astronuc: Nuclear Reactions and Networks in Stars with MESA"
description:  Ebraheem Farag
color_scheme: dark
url: "https://debraheem.github.io"
baseurl: "/astronuc"



# Kramdown with MathJax Configuration
kramdown:
  math_engine: mathjax


plugins:
  - jekyll-remote-theme
  - jemoji
